process REMOVE_RRNA_FEATURECOUNTS {
    /**
     * Filters a featureCounts output file by removing rRNA gene IDs
     * and counts the number of rRNA genes removed for each sample
     *
     * Inputs:
     *   publishdir: Path to the directory to publish the output files to.
     *   counts_file: Path to the input featureCounts output file.
     *   rrna_ids_file: Path to the file containing rRNA IDs (generated by `EXTRACT_RRNA`).
     *
     * Outputs:
     *   Filtered featureCounts output file (rRNA removed).
     *   rRNA count summary file containing the number of rRNA genes removed for each sample.
     */

    publishDir path: { "${ publishdir }" },
        pattern: "FeatureCounts_rRNArm${params.assay_suffix}.tsv",
        mode: params.publish_dir_mode

    input:
        val(publishdir)
        path(counts)
        path(rrna_ids)

    output:
        path("FeatureCounts_rRNArm${params.assay_suffix}.tsv"), emit: counts_rrnarm
        path("rRNA_counts.txt"), emit: rrnarm_summary

    script:
        """
        remove_rrna_featurecounts.py ${counts} ${rrna_ids} FeatureCounts_rRNArm${params.assay_suffix}.tsv
        """
}