process REMOVE_RRNA_FEATURECOUNTS {
    /**
     * Filters a featureCounts output file by removing rRNA gene IDs
     *
     * Inputs:
     *   counts_file: Path to the input featureCounts output file.
     *   rrna_ids_file: Path to the file containing rRNA IDs (generated by `EXTRACT_RRNA`).
     *
     * Outputs:
     *   Filtered featureCounts output file (rRNA removed).
     */

    input:
        path(counts)
        path(rrna_ids)

    output:
        path("FeatureCounts_rRNArm${params.assay_suffix}.tsv"), emit: counts_rrnarm

    script:
        """
        remove_rrna_featurecounts.py ${counts} ${rrna_ids} FeatureCounts_rRNArm${params.assay_suffix}.tsv
        """
}