process REMOVE_RRNA {
    /**
     * Filters a RSEM `genes.results` file by removing rRNA gene IDs
     * and counts the number of rRNA genes removed.
     *
     * Inputs:
     *   rrna_ids_file: Path to the file containing rRNA IDs (generated by `EXTRACT_RRNA`).
     *   genes_results_file: Path to the input `genes.results` file.
     *
     * Outputs:
     *   Filtered gene results file (rRNA removed).
     *   rRNA count summary file.
     */

    publishDir path: { publishdir + "/" + meta.id },
        pattern: { "${meta.id}${params.assay_suffix}_rRNArm.genes.results" },
        mode: params.publish_dir_mode

    input:
        val(publishdir)
        path rrna_ids_file
        tuple val(meta), path("${meta.id}${ params.assay_suffix }.genes.results")

    output:
        path("${meta.id}${params.assay_suffix}_rRNArm.genes.results"), emit: genes_results_rrnarm
        path("${meta.id}${params.assay_suffix}_rRNA_counts.txt"), emit: rrnarm_summary

    script:
        """
        # Extract sample ID from meta variable
        sample_id="${meta.id}"

        # Define output file names
        filtered_file="\${sample_id}${params.assay_suffix}_rRNArm.genes.results"
        counts_file="\${sample_id}${params.assay_suffix}_rRNA_counts.txt"

        echo "Processing: \${sample_id}"

        if [[ ! -s ${rrna_ids_file} ]]; then
            echo "WARNING: No rRNA gene IDs found for \${sample_id}; copying unfiltered genes.results to rRNArm output" >&2
            cp "${meta.id}${ params.assay_suffix }.genes.results" \${filtered_file}
            echo "\${sample_id}: 0 rRNA entries removed." > \${counts_file}
        else
            # Filter rRNA entries
            awk 'NR==FNR {ids[\$1]=1; next} !(\$1 in ids)' ${rrna_ids_file} "${meta.id}${ params.assay_suffix }.genes.results" > \${filtered_file}

            # Count rRNA entries
            rRNA_count=\$(awk 'NR==FNR {ids[\$1]=1; next} \$1 in ids' ${rrna_ids_file} "${meta.id}${ params.assay_suffix }.genes.results" | wc -l)
            echo "\${sample_id}: \${rRNA_count} rRNA entries removed." > \${counts_file}
        fi
        """
}
